### ISSUE TITLE
Suggested modifications of GBADsR read me

### ISSUE THREAD

**Issue by mieghanbruce** [GBADsInformatics/GBADs.R#3]
Can we please reword this sentence in the ReadMe component?

_The DPM is structured according to age (neonate, juenile, and adult) and sex (male and female) and simulations are run in monthly timesteps up to one year._

1. Replace "neonate, juenile, and adult" with "juvenile, sub-adult, and adult"
2. Replace "simulations are run in monthly timesteps up to one year" with "simulations are run in monthly (for small ruminnats and cattle) or weekly (for poultry) timesteps up to one year"

Thank you!

**Comment by jphill01** [comment]
Done!
